name: option_project
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.14.0=py314hd8ed1ab_102
  - debugpy=1.8.17=py314hac9ea21_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libsodium=1.0.20=h99b78c6_0
  - libzlib=1.3.1=h5f15de7_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyh0d26453_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py314h9d33bd4_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.14.0=h1858270_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.0=h4df99d1_102
  - python_abi=3.14=1_cp314
  - pyzmq=27.1.0=py312hd65ceae_0
  - readline=8.3=h0b18652_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.2=py314h0612a62_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - curl-cffi==0.13.0
      - cycler==0.12.1
      - dotenv==0.9.9
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - frozendict==2.4.7
      - idna==3.11
      - import-ipynb==0.2
      - ipynb==0.5.1
      - ivolatility==1.8.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - multitasking==0.0.12
      - nbformat==5.10.4
      - nbimporter==0.3.4
      - numpy==2.3.4
      - pandas==2.3.3
      - peewee==3.18.3
      - pillow==12.0.0
      - protobuf==6.33.1
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.29.0
      - scipy==1.16.3
      - soupsieve==2.8
      - tzdata==2025.2
      - urllib3==2.5.0
      - websockets==15.0.1
      - yahoofinance==0.0.2
      - yfinance==0.2.66
prefix: /opt/anaconda3/envs/option_project
